<?php
/**
 * e-shop - A PHP Package for Laravel Framework start (6.x)
 *
 * @package  eshop
 * @author   Aleksandr Ivanovitch <alex@mwspace.com>
 */

namespace MwSpace\Eshop\Model;

use Throwable;

/**
 * Class Eshop
 * @package MwSpace\Eshop\Model
 */
class EshopException extends \Exception
{
    public function __construct($message = "", $code = 0, Throwable $previous = null)
    {
        parent::__construct($message, $code, $previous);
    }

    public function __toString()
    {
        parent::__toString(); // TODO: Change the autogenerated stub
    }

    public function __wakeup()
    {
        parent::__wakeup(); // TODO: Change the autogenerated stub
    }
}
